export const darkTheme = {
  background: "#1b1b1be7",
  font: "#ffffff",
  button: "#ffffff",
  box: "#ffffff",
  boxfont: "#121214",
  background_navbar: "#121214",
  background_intro_photo: "#fbff00",
  font_navbar: "#ffffff",
  font_contact: "#ffffff",
  font_intro_Typewriter: "#fbff00",
  font_navbar_hover: "#ececec",
  font_contact_icons: "#121214",
  overline_navbar_hover: "overline 3px yellow",
  icon_navbar: "#ffffff",
  background_navbar_mobile: "#1b1b1bfa",
  box_shadow: "0.1em 0.4em 0.4em 0.1em #bbbbbb",
  box_shadow_portfolio: "0.1em 0.1em 0.1em 0.1em #7c7c7ce5",
  btn_lists_box_shadow: "0.3em 0.2em 0.5em #121214",
  contact_form_shadow: "0.4em 0.3em 0.7em #ffff",
  navbar_shadow: "4px 4px 5px #ffffff40",
  portfolio_shadow: "4px 4px 5px #bbbbbb",
  h1: "#fed136",
  h3: "yellow",
  btn_background: "#ffffff",
  btn_background_contact: "yellow",
  btn_font: "#121214",
  btn_font_hover: "#121214",
  skills_font: "#dac400fd",
  skills_background_box: "#292929",
  background_contact_form: "#292929",
  border_input_contact: "1px 0px 2px 2px solid #ffffff",
  background_contact_label: "#292929",
  background_course: "#c5c5c5f5",
  background_contact: "#c5c5c5f5",
  background_contact_icons: "yellow",
  background_contact_icons_hover: "green",
  intro_arrow: "yellow",

}

export const lightTheme = {
  background: "#ececec",
  font: "#252525",
  button: "#121214",
  box: "#252525",
  boxfont: "#ffffff",
  background_navbar: "#eeeeeeee",
  background_intro_photo: "crimson",
  font_navbar: "#121214",
  font_contact: "#121214",
  font_intro_Typewriter: "crimson",
  font_navbar_hover: "gray",
  font_contact_icons: "#ffffff",
  overline_navbar_hover: "overline 3px crimson",
  icon_navbar: "#121214",
  background_navbar_mobile: "#fffffffa",
  box_shadow: "0.1em 0.4em 0.2em #414141",
  box_shadow_portfolio: "0.1em 0.1em 0.1em 0.1em #868686a2",
  contact_form_shadow: "0.4em 0.3em 0.7em #121214",
  navbar_shadow: "4px 4px 5px #00000040",
  btn_lists_box_shadow: "0.4em 0.3em 0.7em #ffffff",
  portfolio_shadow: "4px 4px 5px #bbbbbb",
  h1: "crimson",
  h3: "gray",
  btn_background: "#121214",
  btn_font: "#ffffff",
  btn_font_hover: "#121214",
  btn_background_contact: "yellow",
  skills_font: "#292929",
  skills_background_box: "#ffffff",
  background_contact_form: "#ffffff",
  border_input_contact: "2px solid #ecececcc",
  background_course: "#ecececea",
  background_contact: "#c5c5c5f5",
  background_contact_icons: "#121214",
  background_contact_icons_hover: "green",
  intro_arrow: "crimson",

}